import type { Metadata } from "next";
// import useSWR from "swr";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";

import { Navbar, Footer } from "@/components/widgets";
import { ChildrenProps } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const AuthLayout = (props: ChildrenProps) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {props.children}
                <Footer />
            </body>
        </html>
    );
};

export default AuthLayout;
