import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { NextPageWithLayout } from "./_app";

import { MainLayout } from "@/components/layouts";
import ChatPage from "./chat/chatpage";

const inter = Inter({ subsets: ["latin"] });

const Page: NextPageWithLayout = () => {
    return <ChatPage />;
};

Page.getLayout = (children: React.ReactElement) => {
    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MainLayout>
                <main className={"brainz-chat"}>{children}</main>
            </MainLayout>
        </React.Fragment>
    );
};

export default Page;
