import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { NextPageWithLayout } from "./_app";

import styles from "@/styles/Home.module.css";
import { MainLayout } from "@/components/layouts";

const inter = Inter({ subsets: ["latin"] });

const Page: NextPageWithLayout = () => {
    return <h1>3000</h1>;
};

Page.getLayout = (children: React.ReactElement) => {
    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <MainLayout>
                <main className={"brainz-chat"}>{children}</main>
            </MainLayout>
        </React.Fragment>
    );
};

export default Page;
